### ISSUE TITLE
MoonZoon version + bug

### ISSUE THREAD

**Issue by MartinKavik** [rsdlt/wasm-vigenere-cipher#1]
Hi, 
- I've created a MoonZoon version: [github.com/MoonZoon/vigenere-cipher](https://github.com/MoonZoon/vigenere-cipher)
- I've probably found a bug in the [demo](https://wasm-vigenere-cipher.onrender.com/): try to write `Martin K` into it.

@rsdlt I've tried to contact you directly but mails fail with `Address not found` and Twitter messages are probably disabled.

**Comment by rsdlt** [comment]
Hi @MartinKavik thanks for bringing the bug to my attention, will review. Odd that my email failed, did you try rsdlt@pm.me? Thank you.

**Comment by rsdlt** [comment]
Hi @MartinKavik, thanks again for raising the issue. It's now fixed in release v.0.1.2 Cheers!

**Comment by MartinKavik** [comment]
> Hi @MartinKavik thanks for bringing the bug to my attention, will review. Odd that my email failed, did you try [rsdlt@pm.me](mailto:rsdlt@pm.me)? Thank you.

![image](https://user-images.githubusercontent.com/18517402/194409838-0c5c7a8d-89b3-4f5d-9cb0-48a2f11f492d.png)

I've just copied the only address with a typo... and it's a bit hard to notice it :) 

(Feel free to remove this comment because it's a bit off-topic)
